# .prettierrc.yml
# View options here: https://prettier.io/docs/en/options.html
# You can install the Prettier plugin for your editor https://prettier.io/docs/en/editors.html

printWidth: 100
parser: flow
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
trailingComma: "es5"
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: "avoid"
